# The TextEditor settings file

# The default font size to display text at
defaultFontSize: 16
# Options: MONOSPACED, SERIF, SANS_SERIF
defaultFont: "MONOSPACED"

# Colour scheme options
background: "#FFFFFF"
fontColour: "#000000"