# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# Runs all unit tests with maven before attempting to build. Also generates a PMD report with the build

name: Build Artifacts and Generate PMD

# Build artifacts when pushing to main
on:
  push:
    branches: [ "main" ]
  # Allow manual build trigger  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
      # Runs test in maven lifecycle
    - name: Build with Maven
      run: mvn -B --update-snapshots package --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - run: cp target/config.yml staging
    - uses: actions/upload-artifact@v3
      with:
        name: Application Files
        path: staging
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'ruleset.xml'
        analyzeModifiedFilesOnly: false