# This workflow will run all tests with maven and ensure the project compiles successfully
name: Java CI with Maven

on:
  pull_request_target:
        branches:
            - main
        types: [opened, reopened, edited, synchronize]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn test
